language: python

python: "3.6"

install:
  - pip install flake8
  - pip install -r requirements.txt

before_script:
  - flake8 .

script:
  - python -m unittest discover

notifications:
  email: false
